kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: go-build
    image: golang:alpine
    commands:
    - go env
    - apk update && apk upgrade && apk add --no-cache git
    - go get ./...
    - go build -o wechat-work-message-push-go
    - ./wechat-work-message-push-go -v

  - name: docker-build
    image: plugins/docker
    settings:
      repo:  cloverzrg/wechat-work-message-push-go
      tags: latest
      username:
        from_secret: dockerhub-username
      password:
        from_secret: dockerhub-password




